# Generated by Django 4.1.1 on 2022-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
