# Generated by Django 4.1.1 on 2022-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
